format_version: 3
pipelines:
- name: lambda-deployment
  label_template: '${COUNT}'
  materials:
  - git: 'https://github.com/Saurav0310/test-lambda.git'
    branch: main
  stages:
  - name: Build
    jobs:
    - name: ExecuteCommands
      tasks:
      - exec:
          command: |
            # Run some Linux commands
            echo "Hello, World!"
            ls -al
            mkdir output
            cp file.txt output/
